---
name: 🔄 Validate Renovate Configuration

on:
  merge_group: {}
  pull_request:
    paths: [renovate.json]
permissions: {}

jobs:
  validate:
    name: ✅ Validate Renovate config
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*

      - name: 📦 Install renovate
        run: npm install -g renovate

      - name: 🔍 Validate Renovate config files
        run: renovate-config-validator renovate.json
